### ISSUE TITLE
Packet encoding fails: The value of "offset" is out of range.

### ISSUE THREAD

**Issue by DSorlov** [mafintosh/dns-packet#63]
**Experimenting a bit with creating packages using the encode method. The below package returns an error:**
_RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 971. Received 1013_

const dnsPacket = require('dns-packet')
const buf = dnsPacket.encode({
  type: 'query',
  id: 23751,
  flags: 256,
  questions: [ { type: 'A', name: 'google.com' } ]
})

Perhaps this is related to the issue here: https://github.com/mafintosh/dns-packet/issues/60

Stacktrace:
_at Object.question.decode (C:\sources\lab\node_modules\dns-packet\index.js:1417:31)
at decodeList (C:\sources\lab\node_modules\dns-packet\index.js:1537:19)
at Object.exports.decode (C:\sources\lab\node_modules\dns-packet\index.js:1477:12)
at IncomingMessage.<anonymous> (C:\sources\lab\buildpacket.js:30:35)_

**Comment by DSorlov** [comment]
Never mind, this was due to a memory/strcopy error on my part due to threading/semaphore issues.
